### ISSUE TITLE
Invalid documentation for colors (error compiling template)

### ISSUE THREAD

**Issue by tristanbes** [euvl/vue-js-toggle-button#10]
Webpack reports `Error compiling template: invalid expression: :color="#82C7EB"`

for 

```html
    <toggle-button
      @change="changeApplyQueueEmmiter"
      :value="false"
      :color="#82C7EB"
      :sync="true"
      :labels="{checked: 'apply', unchecked: 'apply_queue'}"
    />
```

How the color syntax should be noted ?

**Comment by euvl** [comment]
It is not a plugin error @tristanbes 

if you bind a String variable you should either use  `color="#82C7EB"` or  `:color=" '#82C7EB' "` notation

**Comment by tristanbes** [comment]
Yes sorry, I just copied paste from the documentation and got this error. Might me misleading for vue newcomers that doesn't know (yet) the variable biding vs string :-)
