### ISSUE TITLE
Labels no longer allow for HTML

### ISSUE THREAD

**Issue by axtg** [euvl/vue-js-toggle-button#101]
Seems like the latest version has some impact on being able to show HTML for labels (e.g. <i class="fa fa-check"></i>). Without any other code changes, this now parses as text, not the intended tag.

Temporary solution can be to define direct unicode characters (✔ and ✖ in my case).

**Comment by euvl** [comment]
You can use (checked/unchecked) slots now 

```
  From the code: 

  <slot name="checked">
        <template>{{labelChecked}}</template>
    </slot>
```
