### ISSUE TITLE
Error mounting the component

### ISSUE THREAD

**Issue by ckgagan** [euvl/vue-js-toggle-button#11]
Hi
I liked your toggle button and thought to implement. However, I got following error while implementing it.
I am using vue 2.3.4, and the error is
```js
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <ToggleButton>
       <DsVendorIndex> at /home/ck_gagan/dev/my_projects/vue-apps/test-proj/src/components/ds_vendors/index.vue
         <Hello> at /home/ck_gagan/dev/my_projects/vue-apps/test-proj/src/components/Hello.vue
           <App> at /home/ck_gagan/dev/my_projects/vue-apps/test-proj/src/App.vue
             <Root>
```
I have added following code in the component that uses toggle button
```js
import ToggleButton from 'vue-js-toggle-button'
```
and manually imported it using
```js
components: {ToggleButton}
```
 and added 

`<toggle-button :value="true" :labels="{checked: 'Foo', unchecked: 'Bar'}"/>`

where I wanted to display the toggle button,

What have I missed

**Comment by euvl** [comment]
Hi, you don't have to include it as a component.

Just do 
```
import ToggleButton from 'vue-js-toggle-button'
Vue.use(ToggleButton)
```

For more info check readme, thanks 👍
