### ISSUE TITLE
Could not find a declaration file for module 'vue-js-toggle-button'

### ISSUE THREAD

**Issue by erickAvSanti** [euvl/vue-js-toggle-button#117]
Could not find a declaration file for module 'vue-js-toggle-button'. '/home/erick/git-projects/saps-vue/node_modules/vue-js-toggle-button/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/vue-js-toggle-button` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-js-toggle-button';`
    87 | const momentjs = require('moment');
    88 | 
  > 89 | import ToggleButton from 'vue-js-toggle-button'
       |                          ^
    90 |  
    91 | Vue.use(ToggleButton)
    92 | 
Version: typescript 3.5.2

**Comment by ositowang** [comment]
This is a javascript based component, not typescript, you need to create the `d.ts` file by yourself, I think
