### ISSUE TITLE
Attach a v-model

### ISSUE THREAD

**Issue by SuperKiwi** [euvl/vue-js-toggle-button#12]
Hello @euvl and well done for this nice package.
My question is the following : 
Is it possible to bind a `v-model` to the component ? I would like to access the value of the toggle button.
Or maybe you have an other idea of how I could perform this ?
Thank you

**Comment by euvl** [comment]
Thanks for kind words. You can get value of the component using `@change` event. 

Example: 
```vue
<toggle-button
            :value="false"
            @change="updateValue"/>
```

```
...
updateValue (event) {
  // event.value - is a current state of the component (true/false)
}
...
```

**Comment by SuperKiwi** [comment]
Thank you for your anwser @euvl 
But in fact, I am trying to catch the value of the toggle button.
When I click on another button I want to catch the value of the toggle button.
But it seems I cannot.

**Comment by coderjz** [comment]
@euvl Came here to ask for this also, I'm trying out your package and expected the v-model to just work. I'm going to use the value callback for now.

I see the help wanted tag, I'm fairly new at Vue JS but might be able to take a stab at this.

**Comment by ejlocop** [comment]
@euvl instead of 
```
this.$emit('change', {value: this.toggled, srcEvent: event})
```
alone. try to add this below

```
this.$emit('input', this.toggled);
```

**Comment by Bronco84** [comment]
I'd also like to see this. I'm using the toggle to change the admin status of a user, but I want the toggle state to depend on the success of the api call. Or as an alternative, provide a "before change" event to allow the call and response and if successful, it slides the toggle.

**Comment by ouraios** [comment]
I've just made a pull request to handle the v-model binding.

**Comment by euvl** [comment]
@ouraios, @Bronco84 @ejlocop, @coderjz, @SuperKiwi

Merged and published 👍
