### ISSUE TITLE
Reset the toggle on a external event

### ISSUE THREAD

**Issue by sabya14** [euvl/vue-js-toggle-button#17]
Hi,
I want to change the state of the toggle to false,on clicking a diffrent button, tried by changing the value of the value prop and with sync true, but it doesnt seem to work.

```vue
<toggle-button :value=toggleMenu @change="toggleView" 
v-if="toggleShow"  :sync="true" :labels="false"
:width=60 :height=30  ></toggle-button>
```

on click i am doing 
this.toggleMenu = false,
but still it does not reset

**Comment by euvl** [comment]
Looks fine to me, take a look in demo, line 52:
https://github.com/euvl/vue-js-toggle-button/blob/master/demo/src/App.vue#L52
