### ISSUE TITLE
Server-side rendered app support

### ISSUE THREAD

**Issue by ABleas** [euvl/vue-js-toggle-button#18]
I'm using [Nuxt.js](https://nuxtjs.org/) and server-side rendering, which means there is no `document`. The webpack module in `/dist` appears to try to reference `document` in a few places. I didn't look too much into what it's used for, but it leads to errors when I include this package in my project.

I got around this by taking just the Vue component `src/Button.vue` for my implementation, but something to consider? 😄

**Comment by euvl** [comment]
Hi @ABleas,

Absolutely, ssr support is in todo list 😄

**Comment by euvl** [comment]
Weird, there is no reference to document in the project, i think i will just rebuild it with `target:node`  and it will do.

**Comment by euvl** [comment]
Should work in `v1.1.5`. Let me know if you will have any issues with it. (take look in readme too pls)

**Comment by MSergiu7** [comment]
I'm still getting this error with the latest version. Any suggestion ?
