### ISSUE TITLE
Failed to mount component

### ISSUE THREAD

**Issue by claide** [euvl/vue-js-toggle-button#19]
Hi, I tried to use the plugin for my app with Vue 2 but got a _Vue warn_ like below

> [Vue warn]: Failed to mount component: template or render function not defined. 
found in ---> <ToggleButton

Already installed the plugin via npm.

Inside vue component:
```
import ToggleButton from 'vue-js-toggle-button'
export default {
  components: { ToggleButton }
}
```

Then I use

`<toggle-button :value="true" :labels="{checked: 'Foo', unchecked: 'Bar'}"/>`

**Comment by claide** [comment]
Aha! Already solved it by creating another component which contains the switch and import it into my main component. Thanks!

**Comment by euvl** [comment]
Hey @claide , please look in the docs, 

```
import ToggleButton from 'vue-js-toggle-button'
Vue.use(ToggleButton)
``` 
Is the only thing you have to do to start using button, ty
