### ISSUE TITLE
Keyboard support?

### ISSUE THREAD

**Issue by nelsonpecora** [euvl/vue-js-toggle-button#21]
These are wonderful-looking and the API is super clear, but I was wondering if there were any plans to add keyboard / tabbing support? I noticed you added `aria` labels (nice!), but it doesn't look like I can tab through them or toggle them via the keyboard.

**Comment by euvl** [comment]
Hey @nelsonpecora,

Till now I didn't even know that one can use radio buttons using keyboard 😄

**Comment by nelsonpecora** [comment]
Looking through the code, I _think_ adding `tabindex` to the `input` might actually give you full keyboard support, but I'd have to test it out.
