### ISSUE TITLE
Cant't see the toggle-button

### ISSUE THREAD

**Issue by ffischer1984** [euvl/vue-js-toggle-button#27]
And get the following message in my console:
[Vue warn]: Failed to mount component: template or render function not defined.  (found in ToggleButton)

tried it with this piece of code:
<toggle-button :value="true" 
               :labels="{checked: 'Foo', unchecked: 'Bar'}"/>
any ideas?
(Browser: Chrome)

**Comment by euvl** [comment]
you didnt send code @ffischer1984
