### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by fracz** [euvl/vue-js-toggle-button#28]
When you open a switch on a mobile device, you should be able to change its state with swipe gesture.

**Comment by euvl** [comment]
I will be happy to review a PR :)

**Comment by fracz** [comment]
I supposed such a response :-) Thank you anyway!

Actually, I have checked all most popular switches and not a single one supports such behavior. 

However, a VanillaJS solutions do exist :-) For example: http://www.javascriptkit.com/javatutors/touchevents2.shtml

Will se what I can do.

**Comment by euvl** [comment]
Yeah, the reason might be that its web , and i would not expect a web button behave the same as native, for various reasons.
