### ISSUE TITLE
Request: value binding

### ISSUE THREAD

**Issue by akhchan99** [euvl/vue-js-toggle-button#29]
Is it possible?

[vue checkbox value binding](https://vuejs.org/v2/guide/forms.html#Checkbox-1)

**Comment by tylerjheslop** [comment]
In toggle options, set sync to true.

**Comment by euvl** [comment]
Hi @akhchan99, as @tylerjheslop rightly said, just use `sync=true`. Take a look in demo for examples and to readme for more info.

**Comment by euvl** [comment]
Can't see reason to do it, why simply not to do: `v-bind:value=" v === 'a' "`?

**Comment by akhchan99** [comment]
Reason being setting the v-model will end up being a boolean again, not 'a' or 'b', and will need a @change event to update the model to the desired value.

Just trying to reduce the extra methods, and use v-model instead of binding the value directly
