### ISSUE TITLE
Add support to change on/off label

### ISSUE THREAD

**Issue by DannyFeliz** [euvl/vue-js-toggle-button#3]
Hi,

Would be cool if you add a prop to change dynamically the label of the toggle when is `on/off` because not always you want the label "on" and "off" in the toggle.

Thanks

**Comment by euvl** [comment]
Hey @DannyFeliz, thanks a lot for your comment! 

I've accepted pull request with custom labels right half an hour ago 😄 
I will test the solution and will update npm version tonight or tomorrow morning.

**Comment by euvl** [comment]
@DannyFeliz added version 1.0.6 with  custom labels, take a look in readme for examples

**Comment by DannyFeliz** [comment]
Thank you very much @euvl 
Keep rocking :guitar:
