### ISSUE TITLE
Button state doesn't change on change in v-model programatically

### ISSUE THREAD

**Issue by ahmedfouzan** [euvl/vue-js-toggle-button#34]
example :

```
<template>
    <toggle-button
       v-model="state"
       :labels="{checked: 'High', unchecked: 'Low'}"
     />
     <v-btn v-on:click="reset()">Reset</v-btn>
</template>
<script>
  export default {
    data () {
        return {
            state: false
        }
    },
    methods: {
        reset () {
            this.state = false
        }
    }
  }
</script>
```

When I toggle the button, _state_ is set to _true_.

When I click on reset button the value of _state_ changes to _false_ but the Toggle Button doesn't show the change.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14348478/32017097-5ab457cc-b9e3-11e7-9eec-a1fbe9bfede8.gif)

**Comment by euvl** [comment]
Hey @ahmedfouzan, Try setting`:sync="true"`. Thanks.

**Comment by ahmedfouzan** [comment]
That worked. Thanks @euvl

**Comment by ankush981** [comment]
I just spent three hours trying to figure this out. This so needs to be in the docs. I'll send a pull request.
