### ISSUE TITLE
Global Configuration

### ISSUE THREAD

**Issue by tochoromero** [euvl/vue-js-toggle-button#39]
It would be really nice if we could specify global settings. For instance, if you want all of your switches to have labels, or globally change the labels to something else.

Thank you very much for the plugin.

**Comment by euvl** [comment]
Hey thanks for a question.

You can create a wrapper with default params. 
It seems to me that it's easily solvable problem and should not be a part of the package.

Links to read:
https://vuejs.org/v2/api/#vm-attrs
https://vuejs.org/v2/api/#vm-listeners

**Comment by tochoromero** [comment]
Fair enough, thank you
