### ISSUE TITLE
How to use it in Vuejs with SSR (not nuxt)

### ISSUE THREAD

**Issue by gaoyike** [euvl/vue-js-toggle-button#41]
Hello,
I am trying to use this plugin in vuejs.

Currently, I have following code in app.js

`
if (process.browser) {
    const toggleButton = require('vue-js-toggle-button/dist/ssr.index')
    Vue.use(toggleButton)
}`

When I call 

`   <toggle-button v-model="private">
                </toggle-button>`

I am having

[Vue warn]: Unknown custom element: <toggle-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I don't know know to register it 

Thanks

**Comment by euvl** [comment]
https://github.com/euvl/vue-notification/issues/11

**Comment by gaoyike** [comment]
Hello,

In my initial post, the first line code already makes sure that the import only happens on the client side of SSR.
