### ISSUE TITLE
Webpack into UMD Module

### ISSUE THREAD

**Issue by craigh411** [euvl/vue-js-toggle-button#42]
Thanks for the great component! At the moment this is being installed globally as a plugin, however, it would work better if it was webpacked in to a UMD module so it could be registered on a per-component basis e.g.:

```
import ToggleButton from 'vue-js-toggle-button'

export default {
  components: {
    ToggleButton
  }
}
```

I can see there is already a `dist` folder, however, that still doesn't allow you to register the component individually, I'd be happy to put in a pull-request when I get the chance if you want.

**Comment by euvl** [comment]
Hey thanks!

What stopes your from doing:

```
import ToggleButton from 'vue-js-toggle-button/src/Button'

export default {
  components: {
    ToggleButton
  }
}
```

?

**Comment by euvl** [comment]
Hey any updates on this question? Did it work for you?

**Comment by craigh411** [comment]
@euvl No that didn't work, it looks like I would need to install the `devDependencies` for this project in my project to do that. I've taken a look at the source and it looks like all you need to do is change `src/index.js` to:

```
import Button from './Button.vue'

export default Button
```

The webpack config already looks like it outputs a UMD module, so it's just a case of removing the plugin registration - which only serves to make the component less flexible by forcing global registration - and then bumping the major version to reflect the breaking change.

**Comment by euvl** [comment]
Nah I am not going to release a major version and change the way it works for hundreds of people just to fit one use-case  😄

**Comment by craigh411** [comment]
Fair enough, it's not a problem for me at the moment, I just don't like muddying my code with global component registration as it can lead to problems down the line and it's not really what Vue's plugin functionality was intended for. Thanks anyway, it's still a great component. :smile

**Comment by euvl** [comment]
Thanks 😄
