### ISSUE TITLE
Button gets "out of sync"

### ISSUE THREAD

**Issue by tristanbes** [euvl/vue-js-toggle-button#43]
Hello,

I use this button to trigger an offer publication status.
So when I use this button, it calls an API to change the state of the publication.

If an errors occurs, it should revert the button to initial position, except it does not. 
Please help me out, thanks.

```js
      switchActiveState(offer) {
        console.log(offer.active);  // returns true in this example
        const matchItem = collection.find(this.items, item => item.id === offer.id);
        if (matchItem) {
          axios
            .post('/switch-status....')
            .then((response) => {
              if (response.data.success === true) {
                matchItem.active = response.data.status;
              } else {
                // if we get anything but success true, we change the value back to initial
                matchItem.active = offer.active;
              }
            })
            .catch(() => {
              // if we get any error, we change the value back to initial
              matchItem.active = offer.active;
            })
          ;
        }
      },
```

```vue
<template slot="status" slot-scope="slotProps">
          <toggle-button
            @change="switchActiveState(slotProps.item)"
            :value="slotProps.item.active"
            color="#20aec4"
            :sync="true"
            :labels="false"
          />
</template>
```

Result in screenshot, after clicking, the `active` on the object is still true, because there were an error: 
![plein_ecran_16_12_2017_12_04](https://user-images.githubusercontent.com/346010/34069837-7021646c-e259-11e7-88c6-b89e64e67127.png)

BUT the button is **"false" instead of true** as if the offer is not published.
![metadata_title_recruitment_center_team](https://user-images.githubusercontent.com/346010/34069883-f3eed5ea-e259-11e7-8c3b-7d6ad2b57bb0.png)

What am I missing there ?

**Comment by float90** [comment]
wo wang to ask zhe same question ,I find zhe same problem, I donot konw why!

**Comment by euvl** [comment]
try caching `offer.active` rather than directly using it by reference.

**Comment by tristanbes** [comment]
Mhh, not sure If I understand you correctly, I tried:

```js
switchActiveState(offer) {
        console.log(offer, offer.active);
        const matchItem = collection.find(this.items, item => item.id === offer.id);
        if (matchItem) {
          axios
            .post(this.getSwitchRouteFor(offer))
            .then((response) => {
              if (response.data.success === true) {
                offer.active = response.data.active;
              } else {
                offer.active = offer.active;
              }
            })
            .catch(() => {
              offer.active = offer.active;
            })
          ;
        }
      },
```

Without any difference.
When it fails, the switch-button still act as if everything were normal, and it's not reverting

**Comment by euvl** [comment]
Try this out of interest:

```
  switchActiveState: offer => {
    const cachedActive = offer.active
    const matchItem = collection.find(this.items, item => item.id === offer.id)
    if (matchItem) {
      axios
        .post('/switch-status....')
        .then(response => {
          if (response.data.success) {
            matchItem.active = response.data.status
          } else {
            matchItem.active = cachedActive
          }
        })
        .catch(() => {
          matchItem.active = cachedActive
        })
    }
  },
```

**Comment by tristanbes** [comment]
When trying your version, it gives: 
`[Vue warn]: Error in event handler for "change": "TypeError: undefined has no properties"`

And when trying to fix it by putting : 
`switchActiveState(offer) {`

It's the same behaviour like before. Even when I do this: 

```
switchActiveState(offer) {
  offer.active = true; 
} 
```

or 
```
switchActiveState(offer) {
  const matchItem = collection.find(this.items, item => item.id === offer.id);
  matchItem.active = true;
} 
```

The button still act on it's on toggling on and off instead of being forced to be "on" all the time. (because of the `.active = true`)

**Comment by tristanbes** [comment]
Full code can be found here if it helps you understand what's wrong : 
https://gist.github.com/tristanbes/bf3ff71f4c091693382f05abfdd9eea5

**Comment by tristanbes** [comment]
thanks to @Kocal, the answer is the following line: `this.$set(offer, 'toggling', true);`

```
switchActiveState(offer) {
        const wasActive = offer.active;
        offer.active = !wasActive;
        this.$set(offer, 'toggling', true);
        axios
          .post(this.getSwitchRouteFor(offer))
          .then((response) => {
            offer.active = response.data.success === true ? response.data.active : wasActive;
          })
          .catch(() => {
            offer.active = wasActive;
          })
          .finally(() => {
            this.$delete(offer, 'toggling');
          });
      },
```

**Comment by Kocal** [comment]
Well, `this.$set()` was just here to set disabled state on the button. 
I don't think that line of code fixed something

**Comment by lukicenturi** [comment]
I just get the same problem and fixed it.

If you use it inside looping, you should add prop `:key` to the toggle button
