### ISSUE TITLE
There's no way to set the name attribute of the input.

### ISSUE THREAD

**Issue by Mouvedia** [euvl/vue-js-toggle-button#46]

**Comment by euvl** [comment]
what?

**Comment by Mouvedia** [comment]
Being able to set the name using a prop would be useful. In particular when you have the same event handler on several toggle buttons and wanna do something different without having to pass an argument to the function and use the event instead. It's not invalid.

**Comment by euvl** [comment]
Done 👍

**Comment by RandomPiche** [comment]
@Mouvedia Did you manage to get to work with Vee-validate ? If so, would you mind sharing with us how ?
I don't really know whether it is a vue-js-toggle related issue or not. If not, close it right away !

Here is the input : 
- the name is set correctly
- v-validate is simply set to 'required' as specified by the doc
- v-model is set and and is correctly updated on change

`<toggle-button :color="{checked: '#484579', unchecked: '#E0E8FC'}" :width="90" :height="35" :labels="{ checked: 'Yes', unchecked: 'No' }" :name="'approval'" v-validate="'required'" v-model="formInfos.approval"/>`

But for some reason, I can't catch the error from the v-validate errorBag on that specific input when it's false. 
FYI it works with a simple : 
`<input type="checkbox" v-validate="'required'" v-model="formInfos.approval">`

What am I missing ?

**Comment by Mouvedia** [comment]
It's been a while now […] you should create a new issue and ask the maintainer directly.
My only advice would to check the [component source](https://github.com/euvl/vue-js-toggle-button/blob/master/src/Button.vue) and inspect the resulting html in your browser.

**Comment by Mouvedia** [comment]
It's been a while now […] you should create a new issue and ask the maintainer directly.
My only advice would be to check the [component source](https://github.com/euvl/vue-js-toggle-button/blob/master/src/Button.vue) and inspect the resulting html in your browser.

My guess is that `v-validate="'required'"` ends up on the `label` root element and not on the `input` like you intended.
