### ISSUE TITLE
Please provide a FontAwesome label example.

### ISSUE THREAD

**Issue by humblecoder** [euvl/vue-js-toggle-button#55]
I've attempted to use FontAwesome as a label to no avail.  I've attempted the following:

```<toggle-button :width="80" :height="30" :value="true" :labels="{checked: '<i class="fas fa-arrows-alt-h"></i>', unchecked: 'Bar'}"/>```

No matter how I organize/adjust my quotes/double-quotes it incorrectly parses the string and simply outputs a portion of the raw HTML.  What am I missing?

**Comment by euvl** [comment]
you have a type, its `fa`, not `fas`

**Comment by humblecoder** [comment]
@euvl I'm trying to use FA5.  Still, that shouldn't matter.  It's a parsing issue.  It's literally outputting the HTML markup.  If there is a version of the icon it will sometimes output it.  Please see attached screenshot.

![screen shot 2018-02-27 at 11 34 19 am](https://user-images.githubusercontent.com/913539/36741167-6bb58ec0-1bb2-11e8-9411-37f9e82f4446.png)

That said, would you mind just presenting an example?

**Comment by humblecoder** [comment]
Actually, copying and pasting the exact same FontAwesome strings into a `data()` object works, however, placing them in-line doesn't.
