### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by vishnu-lumi** [euvl/vue-js-toggle-button#56]
getting this error in my vue project when using `Vue.component('toggle-button', require('vue-js-toggle-button'))` in app.js

**Comment by euvl** [comment]
Please follow the docs, you don't have to do this...

**Comment by MaximeScibetta** [comment]
Same issue but I follow docs

**Comment by euvl** [comment]
if you are following the docs - you will see that you dont have to do `Vue.component('toggle-button', require('vue-js-toggle-button'))` at all 😄
