### ISSUE TITLE
Always displays the error: type check failed for prop "value" if I put v-model

### ISSUE THREAD

**Issue by jeck5895** [euvl/vue-js-toggle-button#58]
Vue version 2.5.13

Sample code:
<toggle-button @change="changeRole(user_type)" :sync="true" v-model="user_type.add_clients"/>

![image](https://user-images.githubusercontent.com/22309354/37197274-13e2f34e-23b5-11e8-9fe1-6b00745c4a32.png)

**Comment by jeck5895** [comment]
@euvl I've manage to remove the type chek error by translating my 1/0 value to true or false. the value of user_type.add_clients is 1. I was just wondering it displays the right result But still throws an error. Just a suggestion, it would be better if vue-toggle can translate 1/0 to true/false. since in tables boolean columns are translated to 1/0

**Comment by euvl** [comment]
Strict typing helps to eliminate errors, i don't think anything should be changed here. 

Also how should know the plugin  better which data type to use if even you didnt know what's your data in that variable?

**Comment by jeck5895** [comment]
I'm not forcing to change change something in the plugin. Since its a toggle it only expects true/false right? Well is some cases  1/0 can be interpret as true/false, as when stored in database.

**Comment by roberto910907** [comment]
I'm using Laravel + Vue and I just changed my model with:
`this.currentClient.status = client.status === 1;
`
No errors now!
