### ISSUE TITLE
Vue cannot find `toggle-button`

### ISSUE THREAD

**Issue by burlesona** [euvl/vue-js-toggle-button#65]
No matter what I try, Vue doesn't seem to be able to find the component <toggle-button>. I'm wondering if the issue is using the name <toggle-button> when the plugin calls it `ToggleButton`. Trying <togglebutton> didn't work either, for whatever reason my build just won't pick it up.

Is there a reason to favor distributing this as a vue plugin rather than just a component? Since the plugin literally just declares the component, why not instead let the user import the `Button` component and then use it how they see fit? That way the end user doesn't have to have this component globally if they're not using it everywhere.

**Comment by burlesona** [comment]
If I ref the raw component from src it fails to build with "cannot parse <template>". I'm not sure exactly what's different about my build setup as I use .vue files for SFC like anyone else, but I'm working on an older app that uses gulp + browserify rather than web pack, and I assume there's some config difference that causes the problem.

In any case I've had no trouble importing various vue components (like `vuedraggable`) etc. when they export a component and I can just import that, but the plugin thing just doesn't take.

I worked around it by just copying the source into my local assets and importing the component from there, but that's not as nice as being able to use the NPM package.

But, my build issues aside, I would guess that many people would rather import the component and declare it in their own components rather than have a global component declared via plugin install. /shrug Maybe just me though.

**Comment by aldencolerain** [comment]
@euvl Thanks for the great component.  Probably this is more just a documentation issue.  Most Vue component packages export a component by default not a plugin although the plugin is very nice.  I think this could be solved by just adding a second short paragraph or sentence showing how to import it as a component since that is what many are used to. It wasn't hard but I did need to look in the source to find the path because it wasn't documented.

**Comment by euvl** [comment]
Hey @aldencolerain , thanks a lot for your PR. Merged 👍
