### ISSUE TITLE
Install guide should mention installing SASS

### ISSUE THREAD

**Issue by AnalyzePlatypus** [euvl/vue-js-toggle-button#67]
## What happens?
`ToggleButton`'s CSS is written in SCSS. (Source [here](https://github.com/euvl/vue-js-toggle-button/blob/cf2dbb9e825f1035e3e73e54c91de9ec44b6293d/src/Button.vue#L240)).

`ToggleButton` fails upon installation if `sass-loader` has not been installed in the `vue-cli` build:
```
 ERROR  Failed to compile with 1 errors                                                                           

This dependency was not found:
./node_modules/vue-js-toggle-button/src/Button.vue
Module not found: Error: Can't resolve 'sass-loader' in '/node_modules/vue-js-toggle-button/src'
```

## What should happen?
* The docs should mention installing the missing dependencies, as mentioned [in the `vue-cli` docs here:](http://vuejs-templates.github.io/webpack/pre-processors.html) `npm install sass-loader node-sass --save-dev`

## Fix
The docs should be updated with the missing step.

**Comment by AnalyzePlatypus** [comment]
Just added a [pull request](https://github.com/euvl/vue-js-toggle-button/pull/68) fixing this.
If it gets merged, this issue can be closed.

**Comment by euvl** [comment]
Nice, ty, merged
