### ISSUE TITLE
Ability to increase height and width

### ISSUE THREAD

**Issue by PunchRockgroin** [euvl/vue-js-toggle-button#7]
This is a beautiful switch, thank you for your efforts. If there could be a way to increase the overall size of the switch, height _and_ width -- perhaps to a size seen in the docs. If this could be controlled through a variable (like 'sm' or 'lg') or other means that would be great. The font size of 10px is a little small for some of my users.

**Comment by euvl** [comment]
Hey, looking into it.

**Comment by euvl** [comment]
@PunchRockgroin, guys, added `height` prop in `vue-js-toggle-button@1.1.0`.
Check out demo (might need to clean cache)
