### ISSUE TITLE
manually check/uncheck toggle button and prevent change event to be fired

### ISSUE THREAD

**Issue by srabanicn** [euvl/vue-js-toggle-button#73]
Hi,

How to manually checked unchecked a toggle button?
I have `Enable All/Disable All` button. By clicking on those buttons I have to check/uncheck all toggle buttons.

And how can I prevent change event to be fired?

Thanks

**Comment by euvl** [comment]
I don't think you will be able to prevent firing the event. If you need to programmatically change the value check the Demo folder, there is an example where values are changed on timer
