### ISSUE TITLE
Inconsistent tracking of checked attribute on input element

### ISSUE THREAD

**Issue by craigballinger** [euvl/vue-js-toggle-button#80]
It appears that the first user interaction with the checkbox input element in the browser triggers an "on" state in the DOM/object property regardless of the value/v-model of the toggle button.

In many use cases, it's probably irrelevant in a practical sense, but when using the toggle in a form that is actually submitted it can become problematic.

Adding :checked="value" seems to resolve the issue. PR submitted. Thanks!

**Comment by euvl** [comment]
Well done, merged
