### ISSUE TITLE
getting error on npm install npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by sidnaik03** [euvl/vue-js-toggle-button#83]
Hi,
When I tried to install **npm i vue-js-toggle-button** getting following error
npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID

**Comment by euvl** [comment]
its smth to do with tls & ssl certificates and has no connection to this plugin,  sorry.
