### ISSUE TITLE
Changing text colour on check

### ISSUE THREAD

**Issue by ecker00** [euvl/vue-js-toggle-button#88]
Am I misunderstanding the documentation or is it not possible to change text colour when toggling on/off? I've got a night/day mode switch where changing text color would be quite nice.

**Comment by euvl** [comment]
i think you need to change it through css

**Comment by ecker00** [comment]
That did the trick, but felt a bit hacky when everything else was so smoothly implemented with property bindings. Using two classes `.text-dark-left` & `.text-dark-right` for fine control worked alright.
```
.text-dark-left .v-switch-label.v-left {
  color: #333 !important;
}
.text-dark-right .v-switch-label.v-right {
  color: #333 !important;
}
```
