### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by TechnicalSuwako** [euvl/vue-js-toggle-button#89]
I'm receiving this problem.

> [Vue warn]: Failed to mount component: template or render function not defined.

In template:

    発行済の証明書を
    <toggle-button
      :value="false"
      :sync="true"
      :color="{
        checked: '#1d99f3',
        unchecked: '#cfbaba'
      }"
      :labels="{
        checked: '表示する',
        unchecked: '非表示する'
      }"
    />

In script:

    import ToggleButton from 'vue-js-toggle-button';
    
    export default {
      components: {
        ToggleButton
      },
    ...

How can it be cured?

**Comment by euvl** [comment]
```
import ToggleButton from 'vue-js-toggle-button'
Vue.use(ToggleButton)
```

**Comment by TechnicalSuwako** [comment]
It already tried, but question was same.

**Comment by laurengranada** [comment]
If you have a main.js file or the file that has all your required npm packages, you need to add the "import ToggleButton from 'vue-js-toggle-button'" there and then add the "Vue.use(ToggleButton)" line in that file as well. 
Then - in your component file where you want to use the Toggle Button, you simply just need to add the "<toggle-button> etc.." in your template code.
