### ISSUE TITLE
Feature Request disable toggle

### ISSUE THREAD

**Issue by woidda** [euvl/vue-js-toggle-button#92]
Initially, one can set the `disabled` property. This is fine in cases where the `disabled` state does not change dynamically. Sometimes -- or actually this is not a rare use case -- you want to be able to change the disabled state depending on the context for example if you are in a `read-only` mode. Then it would be usefull to change that `disabled` state progmatically.

**Comment by willgdjones** [comment]
+1

**Comment by euvl** [comment]
This should work now

**Comment by woidda** [comment]
Thanks @euvl for taking the suggestion. I could not find the corresponding method in your [code](https://github.com/euvl/vue-js-toggle-button/blob/master/src/Button.vue). 
Could you please provide an example and update the docs/ demo? Thanks
