### ISSUE TITLE
Can't get it to work with Vee-Validate

### ISSUE THREAD

**Issue by RandomPiche** [euvl/vue-js-toggle-button#98]
Here is the input : 
- the name is set correctly
- v-validate is simply set to 'required' as specified by the doc
- v-model is set and and is correctly updated on change

`<toggle-button :color="{checked: '#484579', unchecked: '#E0E8FC'}" :width="90" :height="35" :labels="{ checked: 'Yes', unchecked: 'No' }" :name="'approval'" v-validate="'required'" v-model="formInfos.approval"/>`

But for some reason, I can't catch the error from the v-validate errorBag on that specific input when it's false.
The input appears in the "fields" object generated by the validation plugin, props are updated as well but no error message.

What am I missing ? Is this a known issue ? Is it related to the toggle structure ? If not, please close the issue 💪

FYI it works with a simple : 
`<input type="checkbox" v-validate="'required'" v-model="formInfos.approval">`

_Originally posted by @RandomPiche in https://github.com/euvl/vue-js-toggle-button/issues/46#issuecomment-447060434_

vee-validate@^2.1.2
vue-js-toggle-button@^1.3.0

Thanks for considering my request !

**Comment by euvl** [comment]
hey, i do not know how your directive will work with this component as far it is not input, I also did not use vee-validate
